### ISSUE TITLE
rror: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by danielperez9430** [revir/nodebb-plugin-blog-comments2#10]
2018-03-02T23:44:23.085Z [3194] - [31merror[39m: /assets/templates/comments/admin.js
 Error: ENOENT: no such file or directory, open '/var/www/NodeBB/build/public/templates/comments/admin.tpl'
    at Error (native)

2018-03-02T23:44:13.044Z [3194] - [31merror[39m: /admin/blog-comments
 Error: Failed to lookup view "comments/admin" in views directory "/var/www/NodeBB/build/public/templates"
    at EventEmitter.render (/var/www/NodeBB/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/var/www/NodeBB/node_modules/express/lib/response.js:1008:7)
    at content (/var/www/NodeBB/src/middleware/render.js:83:15)
    at /var/www/NodeBB/node_modules/async/dist/async.js:3866:24
    at replenish (/var/www/NodeBB/node_modules/async/dist/async.js:998:17)
    at /var/www/NodeBB/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/var/www/NodeBB/node_modules/async/dist/async.js:1027:24)
    at /var/www/NodeBB/node_modules/async/dist/async.js:1032:16
    at eachOf (/var/www/NodeBB/node_modules/async/dist/async.js:1103:5)
    at _parallel (/var/www/NodeBB/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/var/www/NodeBB/node_modules/async/dist/async.js:3948:5)
    at async.waterfall.str (/var/www/NodeBB/src/middleware/render.js:78:12)
    at nextTask (/var/www/NodeBB/node_modules/async/dist/async.js:5310:14)
    at next (/var/www/NodeBB/node_modules/async/dist/async.js:5317:9)
    at /var/www/NodeBB/node_modules/async/dist/async.js:958:16
    at /var/www/NodeBB/node_modules/async/dist/async.js:473:16

I used NodeBB v1.7.5.

**Comment by geniot** [comment]
So what was the resolution of this issue? :) I'm seeing a similar error.
