### ISSUE TITLE
Module error with NodeBB 1.12.0

### ISSUE THREAD

**Issue by Marlin-Na** [revir/nodebb-plugin-blog-comments2#13]
I got the following error in NodeBB log after activating the plugin and restarting the server. The plugin also does not show up in the ACP menu.

```
2019-03-09T14:13:08.152Z [6942/25931] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/home/nodebb/node_modules/nodebb-plugin-audio-embed/library.js:11:24)
2019-03-09T14:13:08.186Z [6942/25931] - warn: [deprecated] requiring core modules with `module.parent.require('../src/database.js')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /home/nodebb/node_modules/nodebb-plugin-blog-comments2/library.js:6:25
2019-03-09T14:13:08.187Z [6942/25931] - warn: [deprecated] requiring core modules with `module.parent.require('../../src/database.js')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /home/nodebb/node_modules/nodebb-plugin-blog-comments2/library.js:6:25
2019-03-09T14:13:08.187Z [6942/25931] - error: Error: Cannot find module '../../src/database.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Module.module.require (/home/nodebb/src/plugins/index.js:55:26)
    at /home/nodebb/node_modules/nodebb-plugin-blog-comments2/library.js:6:25
    at Object.<anonymous> (/home/nodebb/node_modules/nodebb-plugin-blog-comments2/library.js:328:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
2019-03-09T14:13:08.189Z [6942/25931] - warn: [plugins] Unable to parse library for: nodebb-plugin-blog-comments2
```
Perhaps it can be fixed with https://github.com/psychobunny/nodebb-plugin-blog-comments/commit/41775e710e73e3475e9591958a728f5a6fd25453 ? Please let me know if you want a pull request.

**Comment by zozo6015** [comment]
I have the same issue,
